### ISSUE TITLE
Device boot looping

### ISSUE THREAD

**Issue by mhfaruk** [google/android-management-api-samples#2]
Recently we are working on android management api.we have enrolled 500+ devices.some of these devices get restarted again and again.Is there any chance that this api responsible for this kind of bootloop issue??

**Comment by syefulislam** [comment]
I am also faching same problem. After enrollemnt, some of devices generate bootloop.

**Comment by nkostylev** [comment]
Have you joined the EMM community?
https://developers.google.com/android/management/join

**Comment by syefulislam** [comment]
All ready fill up form, after getting auto reply mail, not yet any response.

**Comment by fredast** [comment]
Closing after more than a year of inactivity.
