### ISSUE TITLE
Quickstart page no longer working?

### ISSUE THREAD

**Issue by charles-hennge** [google/android-management-api-samples#4]
I have tried using the code on quckstart page and it no longer seems to work:

1) Both Create an enterprise and Create a policy fail with the following error:
   "Caller is not authorized to manage project."
   
2) Create a policy fails even if the associated account has an Enterprise and has permissions to manage the project and Enterprise associated with it.

**Comment by fredast** [comment]
Hi Charles,

I just tried and it works fine for me.

> Caller is not authorized to manage project.

This error means that the account used to authenticate the request (when running `credentials = flow.run_console()`) doesn't have permission for the project selected above (`cloud_project_id = ''`). 

You can visit the [IAM page](https://console.cloud.google.com/iam-admin/iam) in the Cloud Console to configure permissions. Check that the account has "Owner", "Editor" or "Android Management User" role and that the project ID in the URL matches the one used in the quickstart page.

Hope this helps,
Fred

**Comment by charles-hennge** [comment]
Thanks for responding. My account has all of those permissions (and more at this point). I have created multiple accounts now and multiple enterprises and keep running into the same problem.

The only thing that makes sense at this point is that somehow I have the wrong enterprise ID. Is there a way to get the correct enterprise ID for a google cloud account you are the owner/editor/administrator of? The values found in the menu are the wrong format (the api seems to want an alphanumeric value of a certain length?) and the page I found here appears to give me an ID of the correct format when logged in to the associated account, but the permissions are always denied:

https://play.google.com/work/adminsettings

**Comment by fredast** [comment]
If you've lost the enterprise ID you can get it from https://play.google.com/work/adminsettings indeed. There is no other way to get it.

But if you create a new enterprise from the quickstart guide you shouldn't need to do that since the enterprise ID is returned when creating the enterprise.

**Comment by isness** [comment]
I have the same problem. However, the project and the internal app belongs to the user within the organisation. The enterprise ID is correct (taken from Google Play organisation information). I've granted the organisation user Android Management User, Editor, Owner, Organisation Administrator roles, but still get the same "Caller is not authorized to manage project." error. 

Any ideas?
