### ISSUE TITLE
Auth erro

### ISSUE THREAD

**Issue by Techiepankh** [google/android-management-api-samples#5]
using this quickstart.ipynb 
I'm getting this error
You can’t sign in because "myapp" sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of myapp, see [error details](https://accounts.google.com/).
Error 400: invalid_request

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

This is the code which is running

from apiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow

CLIENT_CONFIG = {
    'installed': {
        'client_id':'----------------------------------------------------------',
        'client_secret': '------------------------------------------------------',
        'auth_uri':'https://accounts.google.com/o/oauth2/auth',
        'token_uri':'https://oauth2.googleapis.com/token'
    }
}
SCOPES = ['https://www.googleapis.com/auth/androidmanagement']

flow = InstalledAppFlow.from_client_config(CLIENT_CONFIG, SCOPES)
credentials = flow.run_console()

androidmanagement = build('androidmanagement', 'v1', credentials=credentials)

print('\nAuthentication succeeded.')

**Comment by fredast** [comment]
This should now be fixed with [this change](https://github.com/google/android-management-api-samples/commit/37335b1555643753e9600efbed5175ecf266c3dc). Thank you!
