### ISSUE TITLE
Error 400: invalid request 

### ISSUE THREAD

**Issue by censusg** [google/android-management-api-samples#6]
Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

**Comment by fredast** [comment]
Thank you for reporting. This should now be fixed with [this change](https://github.com/google/android-management-api-samples/commit/37335b1555643753e9600efbed5175ecf266c3dc).
